This model is #9 among the tests I made.

### Reading data from file

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Read the data
X_full = pd.read_csv('input/train.csv', index_col='Id') 
X_test = pd.read_csv('input/test.csv', index_col='Id')

X = X_full.copy()
# Remove rows with missing target, separate target from predictors
X.dropna(axis=0, subset=['SalePrice'], inplace=True)
y = X.SalePrice
X.drop(['SalePrice'], axis=1, inplace=True)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

### Inspecting data to get some insight from it

Maybe I should've starting the investigation after splitting the data into training and validation

In [2]:
# X.head()
# X.shape

In [3]:
# X.info()

In [4]:
# X.describe()

In [5]:
# # %matplotlib inline
# import matplotlib.pyplot as plt
# X.hist(bins=25,figsize=(40,35)) 
# plt.show()

In [6]:
# corr_matrix = X_full.corr()
# corr_matrix['SalePrice'].sort_values(ascending=False)

In [7]:
# from pandas.plotting import scatter_matrix

# attributes = ['SalePrice', 'OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF']
# #               '1stFlrSF','FullBath','TotRmsAbvGrd','YearBuilt']

# scatter_matrix(X_full[attributes], figsize=(40,35))
# plt.show()

In [8]:
# attributes = ['SalePrice', '1stFlrSF','FullBath','TotRmsAbvGrd','YearBuilt']
# # OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF']
# scatter_matrix(X_full[attributes], figsize=(40,35))
# plt.show()

In [9]:
# X_full.plot(kind='scatter', x='GrLivArea', y='SalePrice', alpha=0.1)
# plt.show()

In [10]:
# X_full.plot(kind='scatter', x='1stFlrSF', y='SalePrice', alpha=0.1)
# plt.show()

In [11]:
# X_full.plot(kind='scatter', x='OverallQual', y='SalePrice', alpha=0.1)
# plt.show()

### According to the insights gained, I'll create some new numerical features

In [48]:
X['Total_area'] = X['TotalBsmtSF'] + X['1stFlrSF'] + X['2ndFlrSF'] + X['GrLivArea'] + \
                  X['WoodDeckSF'] + X['OpenPorchSF'] + X['EnclosedPorch'] + \
                  X['3SsnPorch'] + X['ScreenPorch'] + X['PoolArea']

X['Number_of_rooms'] = X['TotRmsAbvGrd'] + X['BsmtFullBath'] + X['BsmtHalfBath'] + \
                       X['FullBath'] + X['HalfBath']
    
X['Number_of_bathrooms'] = X['BsmtFullBath'] + X['BsmtHalfBath'] + X['FullBath'] + X['HalfBath']

X['Bedroom_per_room'] =  X['BedroomAbvGr'] / X['TotRmsAbvGrd']

X['build_per_Total_area'] =  (X['TotalBsmtSF'] + X['1stFlrSF'] + X['2ndFlrSF'] + X['GrLivArea'] + \
                              X['WoodDeckSF'] + X['OpenPorchSF'] + X['EnclosedPorch'] + \
                              X['3SsnPorch'] + X['ScreenPorch'] + X['PoolArea']) / X['LotArea']

X_test['Total_area'] = X_test['TotalBsmtSF'] + X_test['1stFlrSF'] + X_test['2ndFlrSF'] + X_test['GrLivArea'] + \
                       X_test['WoodDeckSF'] + X_test['OpenPorchSF'] + X_test['EnclosedPorch'] + \
                       X_test['3SsnPorch'] + X_test['ScreenPorch'] + X_test['PoolArea']

X_test['Number_of_rooms'] = X_test['TotRmsAbvGrd'] + X_test['BsmtFullBath'] + X_test['BsmtHalfBath'] + \
                            X_test['FullBath'] + X_test['HalfBath']
    
X_test['Number_of_bathrooms'] = X_test['BsmtFullBath'] + X_test['BsmtHalfBath'] + \
                                X_test['FullBath'] + X_test['HalfBath']

X_test['Bedroom_per_room'] =  X_test['BedroomAbvGr'] / X_test['TotRmsAbvGrd']

X_test['build_per_Total_area'] =  (X_test['TotalBsmtSF'] + X_test['1stFlrSF'] + X_test['2ndFlrSF'] + \
                                   X_test['GrLivArea'] + X_test['WoodDeckSF'] + X_test['OpenPorchSF'] + \
                                   X_test['EnclosedPorch'] + X_test['3SsnPorch'] + X_test['ScreenPorch'] + \
                                   X_test['PoolArea']) / X_test['LotArea']

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Total_area,Number_of_rooms,Number_of_bathrooms,Bedroom_per_room,build_per_Total_area
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,6,2010,WD,Normal,2934.0,6.0,1.0,0.400000,0.252452
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,12500,6,2010,WD,Normal,4416.0,8.0,2.0,0.500000,0.309525
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,3,2010,WD,Normal,4432.0,9.0,3.0,0.500000,0.320463
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,6,2010,WD,Normal,4530.0,10.0,3.0,0.428571,0.453999
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,0,1,2010,WD,Normal,4066.0,7.0,2.0,0.400000,0.812388

In [13]:
# # Get list of categorical variables
# s = (X_test.dtypes == 'object')
# object_cols = list(s[s].index)

# print("Categorical variables:")
# print(object_cols)

#### Evaluation the correlation of the features after adding new ones

In [14]:
# corr_matrix = X_full.corr()
# corr_matrix['SalePrice'].sort_values(ascending=False)

In [15]:
# # attributes = ['SalePrice', '1stFlrSF','FullBath','TotRmsAbvGrd','YearBuilt']
# attributes = ['SalePrice', 'OverallQual', 'Total_area', 'GrLivArea','Number_of_rooms']
# # OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF']
# scatter_matrix(X_full[attributes], figsize=(40,35))
# plt.show()

### Generating new categorical features

In [16]:
import itertools

cat_features = [cname for cname in X.columns if
                    X[cname].nunique() < 10 and 
                    X[cname].dtype == "object"]

interactions = pd.DataFrame(index=X.index)
interactions_test = pd.DataFrame(index=X_test.index)

# Iterate through each pair of features, combine them into interaction features
for col1, col2 in itertools.combinations(cat_features, 2):
    new_col_name = '_'.join([col1, col2])

    # Convert to strings and combine
    new_values = X[col1] + "_" + X[col2]
    new_values_test = X_test[col1] + "_" + X_test[col2] # Test must have the same number of features

    interactions[new_col_name] = new_values  
    interactions_test[new_col_name] = new_values_test

#     print(interactions[new_col_name])

In [17]:
# s = list(interactions.columns)
# print(s)

In [18]:
# # Get list of categorical variables
# s = (interactions_test.dtypes == 'object')
# object_cols = list(s[s].index)

# print("Categorical variables:")
# print(object_cols)

### Adding new categorical features to the DataFrame

In [49]:
int_X = X.copy()
# int_X = int_X.join(interactions)

int_X_test = X_test.copy()
# int_X_test = int_X_test.join(interactions_test)
# int_X_test.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Total_area,Number_of_rooms,Number_of_bathrooms,Bedroom_per_room,build_per_Total_area
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,6,2010,WD,Normal,2934.0,6.0,1.0,0.400000,0.252452
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,12500,6,2010,WD,Normal,4416.0,8.0,2.0,0.500000,0.309525
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,3,2010,WD,Normal,4432.0,9.0,3.0,0.500000,0.320463
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,6,2010,WD,Normal,4530.0,10.0,3.0,0.428571,0.453999
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,0,1,2010,WD,Normal,4066.0,7.0,2.0,0.400000,0.812388

In [20]:
# # Get list of categorical variables
# s = (interaction_X_test.dtypes == 'object')
# object_cols = list(s[s].index)

# print("Categorical variables:")
# print(object_cols)

### Before any imputation and splitting, let's get rid of the features with hign number of null values

In [51]:
# Enumerating columns with more than 20% of empty lines 
cols_with_missing_limit = [col for col in int_X.columns if int_X[col].isnull().sum() > 250] 
# print(cols_with_missing_limit)
int_X.drop(cols_with_missing_limit, axis=1, inplace=True)
int_X_test.drop(cols_with_missing_limit, axis=1, inplace=True)
# int_X_test.head()

### Splitting

In [22]:
# Break off validation set from training data
X_train, X_valid, y_train, y_valid = train_test_split(int_X, y, train_size=0.8, test_size=0.2)

### Imputation

I've decided to use frequency as the imputer strategy, so I don't need to have two separate steps for imputation. Otherwise, I'd have to use two different imputations.

In [23]:
categorical_cols = [cname for cname in X_train.columns if
                    X_train[cname].nunique() < 10 and 
                    X_train[cname].dtype == "object"]

# Select numerical columns
numerical_cols = [cname for cname in X_train.columns if X_train[cname].dtype in ['int64', 'float64']]

# Keep selected columns only
# my_cols = categorical_cols + numerical_cols
# X_train = X_train[my_cols].copy()
# X_valid = X_valid[my_cols].copy()
# int_X_test = int_X_test[my_cols].copy()

In [24]:
# # Get list of categorical variables
# # s = (interaction_X_test.dtypes == 'object')
# object_cols = list(categorical_cols)

# print("Categorical variables:")
# print(object_cols)

In [25]:
# # Get list of categorical variables
# # s = (interaction_X_test.dtypes == 'object')
# object_cols = list(numerical_cols)

# print("Categorical variables:")
# print(object_cols)

#### Numerical

In [54]:
from sklearn.impute import SimpleImputer

# Make copy to avoid changing original data (when imputing)
num_X_train = X_train.copy()
num_X_valid = X_valid.copy()
num_X_test = int_X_test.copy()

numerical_transformer = SimpleImputer(strategy='most_frequent')
num_X_train = pd.DataFrame(numerical_transformer.fit_transform(num_X_train[numerical_cols]), 
                                    columns = num_X_train[numerical_cols].columns)

num_X_valid = pd.DataFrame(numerical_transformer.transform(num_X_valid[numerical_cols]), 
                                    columns = num_X_valid[numerical_cols].columns)

num_X_test = pd.DataFrame(numerical_transformer.transform(num_X_test[numerical_cols]), 
                                    columns = num_X_test[numerical_cols].columns)

num_X_test.index = int_X_test.index

# imputed_X_train_plus = pd.DataFrame(my_imputer.fit_transform(X_train_plus))
# imputed_X_test = pd.DataFrame(my_imputer.transform(interaction_X_test))
# num_X_test.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,Total_area,Number_of_rooms,Number_of_bathrooms,Bedroom_per_room,build_per_Total_area
Id,,,,,,,,,,,,,,,,,,,,,
1461,20.0,11622.0,5.0,6.0,1961.0,1961.0,0.0,468.0,144.0,270.0,...,120.0,0.0,0.0,6.0,2010.0,2934.0,6.0,1.0,0.400000,0.252452
1462,20.0,14267.0,6.0,6.0,1958.0,1958.0,108.0,923.0,0.0,406.0,...,0.0,0.0,12500.0,6.0,2010.0,4416.0,8.0,2.0,0.500000,0.309525
1463,60.0,13830.0,5.0,5.0,1997.0,1998.0,0.0,791.0,0.0,137.0,...,0.0,0.0,0.0,3.0,2010.0,4432.0,9.0,3.0,0.500000,0.320463
1464,60.0,9978.0,6.0,6.0,1998.0,1998.0,20.0,602.0,0.0,324.0,...,0.0,0.0,0.0,6.0,2010.0,4530.0,10.0,3.0,0.428571,0.453999
1465,120.0,5005.0,8.0,5.0,1992.0,1992.0,0.0,263.0,0.0,1017.0,...,144.0,0.0,0.0,1.0,2010.0,4066.0,7.0,2.0,0.400000,0.812388

In [27]:
# # Get list of categorical variables
# s = (imp_X_test.dtypes == 'object')
# object_cols = list(s[s].index)

# print("Categorical variables:")
# print(object_cols)
# print(num_X_test.head())


# s = (num_X_test.dtypes == ('float64') ) 
# num_cols = list(s[s].index)
# print(num_cols)

#### Categorical

In [57]:
# from sklearn.impute import SimpleImputer

cat_X_train = X_train.copy()
cat_X_valid = X_valid.copy()
cat_X_test = int_X_test.copy()

# Imputation
categorical_transformer = SimpleImputer(strategy='most_frequent')

cat_X_train = pd.DataFrame(numerical_transformer.fit_transform(cat_X_train[categorical_cols]), 
                                    columns = cat_X_train[categorical_cols].columns)

cat_X_valid = pd.DataFrame(numerical_transformer.transform(cat_X_valid[categorical_cols]), 
                                    columns = cat_X_valid[categorical_cols].columns)

cat_X_test = pd.DataFrame(numerical_transformer.transform(cat_X_test[categorical_cols]), 
                                    columns = cat_X_test[categorical_cols].columns)

cat_X_test.index = num_X_test.index
# imputed

# imputed_X_train_plus = pd.DataFrame(my_imputer.fit_transform(X_train_plus))
# imputed_X_test = pd.DataFrame(my_imputer.transform(interaction_X_test))

# imputed_X_train_plus.columns = X_train_plus.columns
# imputed_X_test.columns = interaction_X_test.columns
cat_X_test.head()

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Condition1,Condition2,BldgType,...,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,RH,Pave,Reg,Lvl,AllPub,Inside,Gtl,Feedr,Norm,1Fam,...,SBrkr,TA,Typ,Attchd,Unf,TA,TA,Y,WD,Normal
1462,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Norm,Norm,1Fam,...,SBrkr,Gd,Typ,Attchd,Unf,TA,TA,Y,WD,Normal
1463,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,Norm,Norm,1Fam,...,SBrkr,TA,Typ,Attchd,Fin,TA,TA,Y,WD,Normal
1464,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,Norm,Norm,1Fam,...,SBrkr,Gd,Typ,Attchd,Fin,TA,TA,Y,WD,Normal
1465,RL,Pave,IR1,HLS,AllPub,Inside,Gtl,Norm,Norm,TwnhsE,...,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal

In [29]:
# # Get list of categorical variables
# s = (cat_X_test.dtypes == 'object')
# object_cols = list(s[s].index)
# print("Categorical variables:")
# print(object_cols)

In [30]:
# # Get list of categorical variables
# s = (imputed_X_test.dtypes == 'object')
# object_cols = list(s[s].index)

# print("Categorical variables:")
# print(object_cols)

In [31]:
# cat_imputed_X_train_plus.head()

### Categorical encoding

In [58]:
from sklearn.preprocessing import OneHotEncoder

# cat_features = [cname for cname in imputed_X_train_plus.columns if
#                     imputed_X_train_plus[cname].nunique() < 10 and 
#                     imputed_X_train_plus[cname].dtype == "object"]

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)

OH_X_train = pd.DataFrame(OH_encoder.fit_transform(cat_X_train))
OH_X_valid = pd.DataFrame(OH_encoder.transform(cat_X_valid))
OH_X_test = pd.DataFrame(OH_encoder.transform(cat_X_test))


# One-hot encoding removed index; put it back
OH_X_train.index = cat_X_train.index
OH_X_valid.index = cat_X_valid.index
OH_X_test.index = cat_X_test.index

# OH_cat_imputed_X_train_plus.head()
# Remove categorical columns (will replace with one-hot encoding)
# OH_cat_imputed_X_train_plus_ = OH_cat_imputed_X_train_plus.drop(categorical_cols, axis=1)
# OH_cat_imputed_X_valid_plus_ = OH_cat_imputed_X_valid_plus.drop(categorical_cols, axis=1)
# OH_cat_imputed_X_test_ = OH_cat_imputed_X_test.drop(categorical_cols, axis=1)

# Add one-hot encoded columns to numerical features
# all_imputed_X_train = pd.concat([imputed_X_train_plus, OH_cat_imputed_X_train_plus_], axis=1)
# all_imputed_X_valid = pd.concat([imputed_X_valid_plus, OH_cat_imputed_X_valid_plus_], axis=1)
# all_imputed_X_test = pd.concat([imputed_X_test, OH_cat_imputed_X_test_], axis=1)
# OH_X_test.head()

,0,1,2,3,4,5,6,7,8,9,...,167,168,169,170,171,172,173,174,175,176
Id,,,,,,,,,,,,,,,,,,,,,
1461,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1462,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1463,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1464,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1465,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [33]:
# type(OH_imputed_X_test['MSSubClass'][0])
# OH_imputed_X_test['MSSubClass'].nunique

# s = (OH_X_test.dtypes == 'object')
# print(list(s[s].index))

# MSSubClass, LotArea, OverallQual, YearBuilt, YearRemodAdd, MasVnrArea, BsmtFinSF1, BsmtFinSF2, BsmtUnfSF, 
# TotalBsmtSF, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, TotRmsAbvGrd, GarageYrBlt, GarageArea, WoodDeckSF, 
# OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, MiscVal, MoSold, Total_area, Number_of_rooms, 
# Bedroom_per_room, build_per_Total_area
# OH_X_test.head()

### Joining numerical and categorical DataFrames after imputation and encode

In [59]:
all_X_train = pd.concat([num_X_train, OH_X_train], axis=1)
all_X_valid = pd.concat([num_X_valid, OH_X_valid], axis=1)
all_X_test = pd.concat([num_X_test, OH_X_test], axis=1)
all_X_test.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,167,168,169,170,171,172,173,174,175,176
Id,,,,,,,,,,,,,,,,,,,,,
1461,20.0,11622.0,5.0,6.0,1961.0,1961.0,0.0,468.0,144.0,270.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1462,20.0,14267.0,6.0,6.0,1958.0,1958.0,108.0,923.0,0.0,406.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1463,60.0,13830.0,5.0,5.0,1997.0,1998.0,0.0,791.0,0.0,137.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1464,60.0,9978.0,6.0,6.0,1998.0,1998.0,20.0,602.0,0.0,324.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1465,120.0,5005.0,8.0,5.0,1992.0,1992.0,0.0,263.0,0.0,1017.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [35]:
# all_X_test.head()
# s = (num_X_test.dtypes == ('float64') ) 
# num_cols = list(s[s].index)
# print(num_cols)

### Soon I'll use feature selection

### Defining the model

In [36]:
from xgboost import XGBRegressor

# Define the model
model = XGBRegressor(n_estimators=1000, learning_rate=0.05)

### Training the model

In [37]:
model.fit(all_X_train, y_train)

# preds_test = model.predict(OH_imputed_X_test)

[08:24:09] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.05, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

### Evaluating

In [38]:
from sklearn.metrics import mean_absolute_error

predicted_home_prices = model.predict(all_X_valid)
mean_absolute_error(y_valid, predicted_home_prices)

14389.43386130137

## From here to the bottom I'm trying to figure out what features I should keep

In [39]:
# # print(model.feature_importances_)
# from matplotlib import pyplot
# # plot
# # pyplot.bar(range(len(model.feature_importances_)), model.feature_importances_)
# # pyplot.show()

# from xgboost import plot_importance
# # plot feature importance
# plot_importance(model)
# pyplot.show()

In [46]:
# from sklearn.metrics import accuracy_score
# from sklearn.feature_selection import SelectFromModel
# from numpy import sort

# thresholds = sort(model.feature_importances_)
# for thresh in thresholds:
#     # select features using threshold
#     selection = SelectFromModel(model, threshold=thresh, prefit=True)
#     select_X_train = selection.transform(all_X_train)
#     # train model
#     selection_model = XGBRegressor()
#     selection_model.fit(select_X_train, y_train)
#     # eval model
#     select_X_valid = selection.transform(all_X_valid)
#     predictions = selection_model.predict(select_X_valid)
# #     accuracy = accuracy_score(y_valid, predictions)
#     error = mean_absolute_error(y_valid, predictions)
#     print("Thresh=%.3f, n=%d, Error: %f" % (thresh, select_X_train.shape[1], error))
# all_X_test.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,167,168,169,170,171,172,173,174,175,176
0,20.0,11622.0,5.0,6.0,1961.0,1961.0,0.0,468.0,144.0,270.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,20.0,14267.0,6.0,6.0,1958.0,1958.0,108.0,923.0,0.0,406.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,60.0,13830.0,5.0,5.0,1997.0,1998.0,0.0,791.0,0.0,137.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,60.0,9978.0,6.0,6.0,1998.0,1998.0,20.0,602.0,0.0,324.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,120.0,5005.0,8.0,5.0,1992.0,1992.0,0.0,263.0,0.0,1017.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

### Generating predictions

In [41]:
# Preprocessing of test data, fit model
preds_test = model.predict(all_X_test) 

output = pd.DataFrame({'Id': all_X_test.index, 'SalePrice': preds_test})
output.to_csv('output/submission.csv', index=False)

### Next step

I still need to:

* Select features
* Remove outliers
* Test new model parameters (GridSearch or RandomSearch)
* Pipeline as a second "code"

In [42]:
# from sklearn.compose import ColumnTransformer
# from sklearn.pipeline import Pipeline
# from sklearn.impute import SimpleImputer
# from sklearn.preprocessing import OneHotEncoder

# # Preprocessing for numerical data
# numerical_transformer = SimpleImputer(strategy='most_frequent')

# # Preprocessing for categorical data
# categorical_transformer = Pipeline(steps=[
#     ('imputer', SimpleImputer(strategy='most_frequent')),
#     ('onehot', OneHotEncoder(handle_unknown='ignore', sparse=False))
# ])

# # Bundle preprocessing for numerical and categorical data
# preprocessor = ColumnTransformer(
#     transformers=[
#         ('num', numerical_transformer, numerical_cols),
#         ('cat', categorical_transformer, categorical_cols)
#     ])

In [43]:
# from sklearn.metrics import mean_absolute_error

# # Bundle preprocessing and modeling code in a pipeline
# my_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
#                               ('model_selection', model)
# #                               ('model', model)
#                              ])

# # Preprocessing of training data, fit model 
# my_pipeline.fit(X_train, y_train)


# # Preprocessing of validation data, get predictions
# preds = my_pipeline.predict(X_valid)

# # Evaluate the model
# score = mean_absolute_error(y_valid, preds)
# print('MAE:', score)

In [44]:
# Get back the kept features as a DataFrame with dropped columns as all 0s
# selected_features = pd.DataFrame(model.inverse_transform(X_new), 
#                                  index=X.index,
#                                  columns=X.columns)

# Dropped columns have values of all 0s, keep other columns 
# selected_columns = selected_features.columns[selected_features.var() != 0]

In [45]:
# # Preprocessing of test data, fit model
# preds_test = my_pipeline.predict(X_test) 

# output = pd.DataFrame({'Id': X_test.index, 'SalePrice': preds_test})
# output.to_csv('output/submission.csv', index=False)